src/main/java/net/xiaoxiangshop/entity/Consultation.java
package net.xiaoxiangshop.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Transient;
import javax.validation.constraints.NotEmpty;

import com.baomidou.mybatisplus.annotation.TableField;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * Entity - 咨询
 * 
 */
@Entity
public class Consultation extends BaseEntity<Consultation> {

	private static final long serialVersionUID = -3950317769006303385L;

	/**
	 * 路径
	 */
	private static final String PATH = "/consultation/detail/%d";

	/**
	 * 内容
	 */
	@JsonView(BaseView.class)
	@NotEmpty
	@Lob
	private String content;

	/**
	 * 是否显示
	 */
	private Boolean isShow;

	/**
	 * IP
	 */
	private String ip;

	/**
	 * 会员
	 */
	@JsonView(BaseView.class)
	@TableField(exist = false)
	private Member member;

	/**
	 * 商品
	 */
	@JsonView(BaseView.class)
	@TableField(exist = false)
	private Product product;

	/**
	 * 咨询
	 */
	@TableField(exist = false)
	private Consultation forConsultation;

	/**
	 * 回复
	 */
	@JsonView(BaseView.class)
	@TableField(exist = false)
	private Set<Consultation> replyConsultations = new HashSet<>();

	/**
	 * 店铺
	 */
	@TableField(exist = false)
	private Store store;

	/**
	 * 获取内容
	 * 
	 * @return 内容
	 */
	public String getContent() {
		return content;
	}

	/**
	 * 设置内容
	 * 
	 * @param content
	 *            内容
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * 获取是否显示
	 * 
	 * @return 是否显示
	 */
	public Boolean getIsShow() {
		return isShow;
	}

	/**
	 * 设置是否显示
	 * 
	 * @param isShow
	 *            是否显示
	 */
	public void setIsShow(Boolean isShow) {
		this.isShow = isShow;
	}

	/**
	 * 获取IP
	 * 
	 * @return IP
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * 设置IP
	 * 
	 * @param ip
	 *            IP
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * 获取会员
	 * 
	 * @return 会员
	 */
	public Member getMember() {
		return member;
	}

	/**
	 * 设置会员
	 * 
	 * @param member
	 *            会员
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 获取商品
	 * 
	 * @return 商品
	 */
	public Product getProduct() {
		return product;
	}

	/**
	 * 设置商品
	 * 
	 * @param product
	 *            商品
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * 获取咨询
	 * 
	 * @return 咨询
	 */
	public Consultation getForConsultation() {
		return forConsultation;
	}

	/**
	 * 设置咨询
	 * 
	 * @param forConsultation
	 *            咨询
	 */
	public void setForConsultation(Consultation forConsultation) {
		this.forConsultation = forConsultation;
	}

	/**
	 * 获取回复
	 * 
	 * @return 回复
	 */
	public Set<Consultation> getReplyConsultations() {
		return replyConsultations;
	}

	/**
	 * 设置回复
	 * 
	 * @param replyConsultations
	 *            回复
	 */
	public void setReplyConsultations(Set<Consultation> replyConsultations) {
		this.replyConsultations = replyConsultations;
	}

	/**
	 * 获取店铺
	 * 
	 * @return 店铺
	 */
	public Store getStore() {
		return store;
	}

	/**
	 * 设置店铺
	 * 
	 * @param store
	 *            店铺
	 */
	public void setStore(Store store) {
		this.store = store;
	}

	/**
	 * 获取路径
	 * 
	 * @return 路径
	 */
	@JsonView(BaseView.class)
	@Transient
	public String getPath() {
		if(getProduct()!=null){
			return String.format(Consultation.PATH, getProduct().getId());
		}else{
			return  "";
		}

	}

}

src/main/java/net/xiaoxiangshop/controller/admin/BusinessController.java
package net.xiaoxiangshop.controller.admin;

import java.math.BigDecimal;
import java.util.Date;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import net.xiaoxiangshop.util.XmlUtils;
import org.apache.commons.lang.BooleanUtils;
import org.apache.commons.lang.StringUtils;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import net.xiaoxiangshop.Pageable;
import net.xiaoxiangshop.Results;
import net.xiaoxiangshop.audit.Audit;
import net.xiaoxiangshop.entity.BaseEntity;
import net.xiaoxiangshop.entity.Business;
import net.xiaoxiangshop.entity.BusinessAttribute;
import net.xiaoxiangshop.service.BusinessAttributeService;
import net.xiaoxiangshop.service.BusinessService;
import net.xiaoxiangshop.service.UserService;

/**
 * Controller - 商家
 * 
 */
@Controller("adminBusinessController")
@RequestMapping("/admin/business")
public class BusinessController extends BaseController {

	@Inject
	private BusinessService businessService;
	@Inject
	private UserService userService;
	@Inject
	private BusinessAttributeService businessAttributeService;

	/**
	 * 检查用户名是否存在
	 */
	@GetMapping("/check_username")
	public @ResponseBody boolean checkUsername(String username) {
		return StringUtils.isNotEmpty(username) && !businessService.usernameExists(username);
	}

	/**
	 * 检查E-mail是否存在
	 */
	@GetMapping("/check_email")
	public @ResponseBody boolean checkEmail(Long id, String email) {
		return StringUtils.isNotEmpty(email) && !businessService.emailUnique(id, email);
	}

	/**
	 * 检查手机是否存在
	 */
	@GetMapping("/check_mobile")
	public @ResponseBody boolean checkMobile(Long id, String mobile) {
		return StringUtils.isNotEmpty(mobile) && !businessService.mobileUnique(id, mobile);
	}

	/**
	 * 查看
	 */
	@GetMapping("/view")
	public String view(Long id, ModelMap model) {
		model.addAttribute("businessAttributes", businessAttributeService.findList(true, true));
		model.addAttribute("business", businessService.find(id));
		return "admin/business/view";
	}

	/**
	 * 添加
	 */
	@GetMapping("/add")
	public String add(ModelMap model) {
		model.addAttribute("business", businessService.findAll());
		model.addAttribute("businessAttributes", businessAttributeService.findList(true, true));
		return "admin/business/add";
	}

	/**
	 * 保存
	 */
	@Audit(action = "auditLog.action.admin.business.save")
	@PostMapping("/save")
	public ResponseEntity<?> save(Business business, HttpServletRequest request) {
		if (!isValid(Business.class, BaseEntity.Save.class)) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (businessService.usernameExists(business.getUsername())) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (businessService.emailExists(business.getEmail())) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (businessService.mobileExists(business.getMobile())) {
			return Results.UNPROCESSABLE_ENTITY;
		}

		business.removeAttributeValue();
		for (BusinessAttribute businessAttribute : businessAttributeService.findList(true, true)) {
			String[] values = request.getParameterValues("businessAttribute_" + businessAttribute.getId());
			if (!businessAttributeService.isValid(businessAttribute, values)) {
				return Results.UNPROCESSABLE_ENTITY;
			}
			Object memberAttributeValue = businessAttributeService.toBusinessAttributeValue(businessAttribute, values);
			business.setAttributeValue(businessAttribute, memberAttributeValue);
		}

		business.setBalance(BigDecimal.ZERO);
		business.setFrozenAmount(BigDecimal.ZERO);
		business.setIsLocked(false);
		business.setLockDate(null);
		business.setLastLoginIp(XmlUtils.getIp(request));
		business.setLastLoginDate(new Date());
		business.setStore(null);
		business.setBusinessCashs(null);
		business.setBusinessDepositLogs(null);
		businessService.save(business);
		return Results.OK;
	}

	/**
	 * 编辑
	 */
	@GetMapping("/edit")
	public String edit(Long id, ModelMap model) {
		model.addAttribute("businessAttributes", businessAttributeService.findList(true, true));
		model.addAttribute("business", businessService.find(id));
		return "admin/business/edit";
	}

	/**
	 * 更新
	 */
	@Audit(action = "auditLog.action.admin.business.update")
	@PostMapping("/update")
	public ResponseEntity<?> update(Business business, Long id, Long businessRankId, Boolean unlock, HttpServletRequest request) {
		if (!isValid(business)) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (businessService.emailUnique(id, business.getEmail())) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (businessService.mobileUnique(id, business.getMobile())) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		business.removeAttributeValue();
		for (BusinessAttribute businessAttribute : businessAttributeService.findList(true, true)) {
			String[] values = request.getParameterValues("businessAttribute_" + businessAttribute.getId());
			if (!businessAttributeService.isValid(businessAttribute, values)) {
				return Results.UNPROCESSABLE_ENTITY;
			}
			Object businessAttributeValue = businessAttributeService.toBusinessAttributeValue(businessAttribute, values);
			business.setAttributeValue(businessAttribute, businessAttributeValue);
		}
		Business pbusiness = businessService.find(id);
		if (pbusiness == null) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (BooleanUtils.isTrue(pbusiness.getIsLocked()) && BooleanUtils.isTrue(unlock)) {
			userService.unlock(business);
			businessService.update(business, "username", "encodedPassword", "balance", "frozenAmount", "businessDepositLogs", "businessCashs", "lastLoginIp", "lastLoginDate");
		} else {
			businessService.update(business, "username", "encodedPassword", "balance", "frozenAmount", "businessDepositLogs", "businessCashs", "isLocked", "lockDate", "lastLoginIp", "lastLoginDate");
		}
		return Results.OK;
	}

	/**
	 * 列表
	 */
	@GetMapping("/list")
	public String list(Pageable pageable, ModelMap model) {
		model.addAttribute("page", businessService.findPage(pageable));
		return "admin/business/list";
	}

	/**
	 * 删除
	 */
	@Audit(action = "auditLog.action.admin.business.delete")
	@PostMapping("/delete")
	public ResponseEntity<?> delete(Long[] ids) {
		if (ids != null) {
			for (Long id : ids) {
				Business business = businessService.find(id);
				if (business != null && (business.getBalance().compareTo(BigDecimal.ZERO) > 0 || business.getStore() != null)) {
					return Results.unprocessableEntity("admin.business.deleteExistDepositNotAllowed", business.getUsername());
				}
			}
			businessService.delete(ids);
		}
		return Results.OK;
	}

}

src/main/java/net/xiaoxiangshop/controller/admin/ConsultationController.java
package net.xiaoxiangshop.controller.admin;

import javax.inject.Inject;

import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import net.xiaoxiangshop.Pageable;
import net.xiaoxiangshop.Results;
import net.xiaoxiangshop.entity.Consultation;
import net.xiaoxiangshop.service.ConsultationService;

/**
 * Controller - 咨询
 * 
 */
@Controller("adminConsultationController")
@RequestMapping("/admin/consultation")
public class ConsultationController extends BaseController {

	@Inject
	private ConsultationService consultationService;

	/**
	 * 编辑
	 */
	@GetMapping("/edit")
	public String edit(Long id, ModelMap model) {
		model.addAttribute("consultation", consultationService.find(id));
		return "admin/consultation/edit";
	}

	/**
	 * 更新
	 */
	@PostMapping("/update")
	public ResponseEntity<?> update(Long id, @RequestParam(defaultValue = "false") Boolean isShow) {
		Consultation consultation = consultationService.find(id);
		if (consultation == null) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (isShow != consultation.getIsShow()) {
			consultation.setIsShow(isShow);
			consultationService.update(consultation);
		}
		return Results.OK;
	}

	/**
	 * 列表
	 */
	@GetMapping("/list")
	public String list(Pageable pageable, ModelMap model) {
		model.addAttribute("page", consultationService.findPage(null, null, null, null, pageable));
		return "admin/consultation/list";
	}

	/**
	 * 删除
	 */
	@PostMapping("/delete")
	public ResponseEntity<?> delete(Long[] ids) {
		if (ids != null) {
			consultationService.delete(ids);
		}
		return Results.OK;
	}

}

src/main/java/net/xiaoxiangshop/controller/business/AftersalesController.java
package net.xiaoxiangshop.controller.business;

import java.util.HashMap;
import java.util.Map;

import javax.inject.Inject;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import net.xiaoxiangshop.Pageable;
import net.xiaoxiangshop.Results;
import net.xiaoxiangshop.Setting;
import net.xiaoxiangshop.entity.Aftersales;
import net.xiaoxiangshop.entity.Store;
import net.xiaoxiangshop.exception.UnauthorizedException;
import net.xiaoxiangshop.security.CurrentStore;
import net.xiaoxiangshop.service.AftersalesService;
import net.xiaoxiangshop.service.OrderShippingService;
import net.xiaoxiangshop.util.SystemUtils;

/**
 * Controller - 售后
 * 
 */
@Controller("businessAftersalesController")
@RequestMapping("business/aftersales")
public class AftersalesController extends BaseController {

	@Inject
	private AftersalesService aftersalesService;
	@Inject
	private OrderShippingService orderShippingService;

	/**
	 * 添加属性
	 */
	@ModelAttribute
	public void populateModel(Long aftersalesId, @CurrentStore Store currentStore, ModelMap model) {
		Aftersales aftersales = aftersalesService.find(aftersalesId);
		if (aftersales != null && !currentStore.equals(aftersales.getStore())) {
			throw new UnauthorizedException();
		}
		model.addAttribute("aftersales", aftersales);
	}

	/**
	 * 物流动态
	 */
	@GetMapping("/transit_step")
	public ResponseEntity<?> transitStep(@ModelAttribute(binding = false) Aftersales aftersales, @CurrentStore Store currentStore) {
		Map<String, Object> data = new HashMap<>();

		Setting setting = SystemUtils.getSetting();
		if (StringUtils.isEmpty(setting.getKuaidi100Customer()) || StringUtils.isEmpty(setting.getKuaidi100Key()) || StringUtils.isEmpty(aftersales.getDeliveryCorpCode()) || StringUtils.isEmpty(aftersales.getTrackingNo())) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		data.put("transitSteps", orderShippingService.getTransitSteps(aftersales.getDeliveryCorpCode(), aftersales.getTrackingNo()));
		return ResponseEntity.ok(data);
	}

	/**
	 * 列表
	 */
	@GetMapping("/list")
	public String list(Aftersales.Type type, Aftersales.Status status, @CurrentStore Store currentStore, Pageable pageable, ModelMap model) {
		model.addAttribute("types", Aftersales.Type.values());
		model.addAttribute("statuses", Aftersales.Status.values());
		model.addAttribute("type", type);
		model.addAttribute("status", status);
		model.addAttribute("page", aftersalesService.findPage(type, status, null, currentStore, pageable));
		return "business/aftersales/list";
	}

	/**
	 * 查看
	 */
	@GetMapping("/view")
	public String view(@ModelAttribute(binding = false) Aftersales aftersales, ModelMap model) {
		if (aftersales == null) {
			return UNPROCESSABLE_ENTITY_VIEW;
		}
		if (CollectionUtils.isEmpty(aftersales.getOrderItems())) {
			return UNPROCESSABLE_ENTITY_VIEW;
		}

		Setting setting = SystemUtils.getSetting();
		model.addAttribute("isKuaidi100Enabled", StringUtils.isNotEmpty(setting.getKuaidi100Customer()) && StringUtils.isNotEmpty(setting.getKuaidi100Key()));
		model.addAttribute("aftersales", aftersales);
		System.out.println(">>" + aftersales.getType() + " , " + aftersales.getType().name());
		return "business/aftersales/view";
	}

	/**
	 * 审核
	 */
	@PostMapping("/review")
	public ResponseEntity<?> review(@ModelAttribute(binding = false) Aftersales aftersales, boolean passed) {
		if (aftersales == null) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (!Aftersales.Status.PENDING.equals(aftersales.getStatus())) {
			return Results.UNPROCESSABLE_ENTITY;
		}

		aftersalesService.review(aftersales, passed);
		return Results.OK;
	}

	/**
	 * 完成
	 */
	@PostMapping("/complete")
	public ResponseEntity<?> complete(@ModelAttribute(binding = false) Aftersales aftersales) {
		if (aftersales == null) {
			return Results.UNPROCESSABLE_ENTITY;
		}
		if (!Aftersales.Status.APPROVED.equals(aftersales.getStatus())) {
			return Results.UNPROCESSABLE_ENTITY;
		}

		aftersalesService.complete(aftersales);
		return Results.OK;
	}

}

src/main/java/net/xiaoxiangshop/controller/business/IndexController.java
package net.xiaoxiangshop.controller.business;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller - 商家中心
 * 
 */
@Controller("businessIndexController")
@RequestMapping("/business/index")
public class IndexController extends BaseController {

	/**
	 * 首页
	 */
	@GetMapping
	public String index() {
		return "/business/index";
	}

}

src/main/webapp/WEB-INF/template/business/consultation/edit.ftl
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta name="format-detection" content="telephone=no">
	<meta name="author" content="小象SHOP Team">
	<meta name="copyright" content="小象SHOP">
	<title>${message("business.consultation.edit")} - 小象电商</title>
	<link href="${base}/favicon.ico" rel="icon">
	<link href="${base}/resources/common/css/bootstrap.css" rel="stylesheet">
	<link href="${base}/resources/common/css/iconfont.css" rel="stylesheet">
	<link href="${base}/resources/common/css/font-awesome.css" rel="stylesheet">
	<link href="${base}/resources/common/css/awesome-bootstrap-checkbox.css" rel="stylesheet">
	<link href="${base}/resources/common/css/base.css" rel="stylesheet">
	<link href="${base}/resources/business/css/base.css" rel="stylesheet">
	<!--[if lt IE 9]>
		<script src="${base}/resources/common/js/html5shiv.js"></script>
		<script src="${base}/resources/common/js/respond.js"></script>
	<![endif]-->
	<script src="${base}/resources/common/js/jquery.js"></script>
	<script src="${base}/resources/common/js/bootstrap.js"></script>
	<script src="${base}/resources/common/js/bootstrap-growl.js"></script>
	<script src="${base}/resources/common/js/bootbox.js"></script>
	<script src="${base}/resources/common/js/jquery.nicescroll.js"></script>
	<script src="${base}/resources/common/js/jquery.form.js"></script>
	<script src="${base}/resources/common/js/jquery.cookie.js"></script>
	<script src="${base}/resources/common/js/underscore.js"></script>
	<script src="${base}/resources/common/js/url.js"></script>
	<script src="${base}/resources/common/js/velocity.js"></script>
	<script src="${base}/resources/common/js/velocity.ui.js"></script>
	<script src="${base}/resources/common/js/base.js"></script>
	<script src="${base}/resources/business/js/base.js"></script>
	[#noautoesc]
		[#escape x as x?js_string]
			<script>
			$().ready(function() {
			
				var $delete = $("button.delete");
				
				// 删除
				$delete.delete({
					url: "${base}/business/consultation/delete_reply",
					data: function($element) {
						return {
							consultationId: $element.data("id")
						}
					}
				}).on("success.xiaoxiangshop.delete", function(event) {
					var $element = $(event.target);
					
					$element.closest(".form-group").velocity("fadeOut", {
						complete: function() {
							$(this).remove();
							if ($("button.delete").length < 1) {
								location.reload(true);
							}
						}
					});
				});
			
			});
			</script>
		[/#escape]
	[/#noautoesc]
</head>
<body class="business">
	[#include "/business/include/main_header.ftl" /]
	[#include "/business/include/main_sidebar.ftl" /]
	<main>
		<div class="container-fluid">
			<ol class="breadcrumb">
				<li>
					<a href="${base}/business/index">
						<i class="iconfont icon-homefill"></i>
						${message("common.breadcrumb.index")}
					</a>
				</li>
				<li class="active">${message("business.consultation.edit")}</li>
			</ol>
			<form id="consultationForm" class="ajax-form form-horizontal" action="${base}/business/consultation/update" method="post">
				<input name="consultationId" type="hidden" value="${consultation.id}">
				<div class="panel panel-default">
					<div class="panel-heading">${message("business.consultation.edit")}</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-12 col-sm-6">
								<dl class="items dl-horizontal">
									<dt>${message("Consultation.product")}:</dt>
									<dd>
										<a href="${base}${consultation.product.path}" target="_blank">${consultation.product.name}</a>
									</dd>
									<dt>${message("Consultation.member")}:</dt>
									<dd>
										[#if consultation.member??]
											${consultation.member.username}
										[#else]
											${message("business.consultation.anonymous")}
										[/#if]
									</dd>
									<dt>${message("Consultation.content")}:</dt>
									<dd>${consultation.content}</dd>
									<dt>${message("Consultation.ip")}:</dt>
									<dd>${consultation.ip}</dd>
								</dl>
							</div>
						</div>
						[#if consultation.replyConsultations?has_content]
							[#list consultation.replyConsultations as replyConsultation]
								<div class="form-group">
									<div class="col-xs-3 col-xs-offset-2">
										<p class="form-control-static">${replyConsultation.content}</p>
									</div>
									<div class="col-xs-2">
										<p class="form-control-static text-gray">${replyConsultation.createdDate?string("yyyy-MM-dd HH:mm:ss")}</p>
									</div>
									<div class="col-xs-1">
										<p class="form-control-static">
											<button class="delete btn btn-default btn-xs btn-icon" type="button" title="${message("common.delete")}" data-toggle="tooltip" data-id="${replyConsultation.id}">
												<i class="iconfont icon-close"></i>
											</button>
										</p>
									</div>
								</div>
							[/#list]
						[/#if]
						<div class="form-group">
							<label class="col-xs-3 col-sm-2 control-label">${message("common.setting")}:</label>
							<div class="col-xs-9 col-sm-10">
								<div class="checkbox">
									<input name="_isShow" type="hidden" value="false">
									<input id="isShow" name="isShow" type="checkbox" value="true"[#if consultation.isShow] checked[/#if]>
									<label for="isShow">${message("Consultation.isShow")}</label>
								</div>
							</div>
						</div>
					</div>
					<div class="panel-footer">
						<div class="row">
							<div class="col-xs-9 col-sm-10 col-xs-offset-3 col-sm-offset-2">
								<button class="btn btn-primary" type="submit">${message("common.submit")}</button>
								<button class="btn btn-default" type="button" data-action="back">${message("common.back")}</button>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</main>
</body>
</html>